{% set name = "mtsv_tools" %}


package:
  name: {{ name }}
  version: {{ environ['VERSION'] }}

source:
  path: ../ 

build:
  script_env:
     - VERSION
     - CONDA_BLD_PATH
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - rust>1.29.0
  
test:
  commands:
    - mtsv-build --help > /dev/null
    - mtsv-chunk --help > /dev/null
    - mtsv-binner --help > /dev/null
    - mtsv-collapse --help > /dev/null


about:
  home: https://github.com/FofanovLab/mtsv_tools
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: |
    mtsv_tools contains core tools for alignment-based metagenomic binning

extra:
  recipe_maintainers: tfursten
    
